language: ruby

env:
  - TCL_VERSION=8.5

install:
  - curl -L "http://prdownloads.sourceforge.net/tcl/tcl${TCL_VERSION}-src.tar.gz" | tar xzfv -
  - cd "tcl${TCL_VERSION}/unix"
  - ./configure
  - make
  - sudo make install
  - cd ../..
  - bundle install

script: bundle exec rake
